name       : strace
version    : '5.16'
release    : 8
source     :
    - https://github.com/strace/strace/releases/download/v5.16/strace-5.16.tar.xz : dc7db230ff3e57c249830ba94acab2b862da1fcaac55417e9b85041a833ca285
license    : BSD-3-Clause
summary    : Diagnostic, debugging and instructional userspace utility
component  : programming.tools
description: |
    Strace is a diagnostic, debugging and instructional userspace utility for Linux. It is used to monitor and tamper with interactions between processes and the Linux kernel, which include system calls, signal deliveries, and changes of process state.
homepage   : https://strace.io/
builddeps  :
    - pkgconfig(libunwind)
setup      : |
    %configure --with-libunwind
build      : |
    %make
install    : |
    %make_install
