name       : strace
version    : 4.10
release    : 1
source     :
    - http://downloads.sourceforge.net/project/strace/strace/4.10/strace-4.10.tar.xz : e6180d866ef9e76586b96e2ece2bfeeb3aa23f5cc88153f76e9caedd65e40ee2
license    : BSD-3-Clause
summary    : diagnostic, debugging and instructional userspace utility
description: |
    diagnostic, debugging and instructional userspace utility
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
