name       : strace
version    : 4.19
release    : 4
source     :
    - https://sourceforge.net/projects/strace/files/strace/4.19/strace-4.19.tar.xz : 7c93ebc6c29280f47c24a0eb86873a99ccb2cac6512c60a60ba4ef99ab807281
license    : BSD-3-Clause
summary    : diagnostic, debugging and instructional userspace utility
component  : programming.tools
description: |
    diagnostic, debugging and instructional userspace utility
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
