name       : strace
version    : 4.16
release    : 2
source     :
    - http://downloads.sourceforge.net/project/strace/strace/4.16/strace-4.16.tar.xz : 98487cb5178ec1259986cc9f6e2a844f50e5d1208c112cc22431a1e4d9adf0ef
license    : BSD-3-Clause
summary    : diagnostic, debugging and instructional userspace utility
component  : programming.tools
description: |
    diagnostic, debugging and instructional userspace utility
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
