name       : strace
version    : 4.17
release    : 3
source     :
    - http://downloads.sourceforge.net/project/strace/strace/4.17/strace-4.17.tar.xz : 81f35b085fbb3cfa806eb521a8522ac3406deaccfe121ce35064bad268237419
license    : BSD-3-Clause
summary    : diagnostic, debugging and instructional userspace utility
component  : programming.tools
description: |
    diagnostic, debugging and instructional userspace utility
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
